### ISSUE TITLE
Novel View Synthesis with vertical and horizontal camera move

### ISSUE THREAD

**Issue by zuochongyan** [hyzhou404/HUGS#5]
the reconstruction result in waymo is quite promising.i generate 2 sequences with waymo, one with camera move to the left 1.5m, one with camera move up 1.5m. 
I add a transform in dataset_readers.py/readStudioCameras to represent new view.

![image](https://github.com/hyzhou404/HUGS/assets/9625061/30a9b2aa-b501-4619-8eb3-17fbcb33ab84)

Here Are the generated image。
1.camera move to the left 1.5m
![image](https://github.com/hyzhou404/HUGS/assets/9625061/c0ebc6ed-de41-44ff-802a-08968bfbd581)
the lane on the road seems quite messy.

2.camera move to the top 1.5m
![image](https://github.com/hyzhou404/HUGS/assets/9625061/18d9a769-df54-460e-9058-750e12a2090a)
because the lack of top view constrain in trainset, rendering result is corrupted.

Is this a known phenomeon, or i did the wrong way of generating new views.If it is  a known phenomeon, could you suggest some papers/method which can improve the quality,thanks!

**Comment by hyzhou404** [comment]
Almost all reconstruction methods struggles with the problem of poor rendering quality in extrapolation views. This is because 3D Gaussians are tailored only to fit the training views. So, when the view direction changes drastically from the training views, these methods tend to show artifacts.
However, some studies, such as SGD (Street View Synthesis with Gaussian Splatting and Diffusion Prior), have made efforts to address this issue.

**Comment by zuochongyan** [comment]
I also think priors should be add to solve such problems,thank you for your reference!
